controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_command_joint_name: "front_left_wheel_joint"
    front_right_wheel_command_joint_name: "front_right_wheel_joint"
    rear_left_wheel_command_joint_name: "rear_left_wheel_joint"
    rear_right_wheel_command_joint_name: "rear_right_wheel_joint"
    use_stamped_vel: false 
    kinematics:
      wheels_radius: 0.032
      wheel_separation_width: 0.15708
      wheel_separation_length: 0.136

    cmd_vel_timeout: 0.5
    publish_limited_velocity: false
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
